# Generated by Django 5.1.4 on 2025-01-03 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expensesplit_owed_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='group',
        ),
        migrations.AddField(
            model_name='settlement',
            name='split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='api.expensesplit'),
        ),
    ]
