# Generated by Django 5.1.4 on 2025-01-03 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_settlement_group_settlement_split'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesplit',
            name='owed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='split',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='api.expensesplit'),
        ),
    ]
